### ISSUE TITLE
Where can I get the datasets?

### ISSUE THREAD

**Issue by WenTingTseng** [wuningxi/tBERT#1]
Hello, when I run base_model_bert.py, it can not find the data/MSRP/MSRParaphraseCorpus/msr-para-train.tsv. Where can I get this file and other dataset it seems be lost.

Thanks a lot for your help

**Comment by wuningxi** [comment]
Hi WenTing, 
The easiest way is to download `https://www.dropbox.com/s/thhym7njtgp8uoh/data.tar.gz` as mentioned in the setup instructions. This already contains the preprocessed dataset files in the `cache/` folder.  Please make sure that the tarball is  placed in the tBERT directory and unpacked, so the model can find it. You can check this by going to your tBERT directory and type `ls data/cache/m_*.pickle` which should show you the three MSRP files: 
```data/cache/m_dev_B.pickle   data/cache/m_train_B.pickle   data/cache/m_test_B.pickle```
Alternatively you can download the original datasets, place them in the respective dataset folders and process them from scratch.

**Comment by yugaljain1999** [comment]
Hello, @WenTingTseng @wuningxi when I run base_model_bert.py , i got this error
`Traceback (most recent call last):
  File "base_model_bert.py", line 10, in <module>
    from src.models.tf_helpers import lookup_embedding,initialise_pretrained_embedding
ModuleNotFoundError: No module named 'src'`

Even file system is properly arranged as per instructions in Readme.md
Thanks a lot for help.

**Comment by lattyjiang** [comment]
> Hi WenTing,
> The easiest way is to download `https://www.dropbox.com/s/thhym7njtgp8uoh/data.tar.gz` as mentioned in the setup instructions. This already contains the preprocessed dataset files in the `cache/` folder. Please make sure that the tarball is placed in the tBERT directory and unpacked, so the model can find it. You can check this by going to your tBERT directory and type `ls data/cache/m_*.pickle` which should show you the three MSRP files:
> `data/cache/m_dev_B.pickle data/cache/m_train_B.pickle data/cache/m_test_B.pickle`
> Alternatively you can download the original datasets, place them in the respective dataset folders and process them from scratch.

hello,I want know where can download the original data sets.thank you !!

**Comment by wuningxi** [comment]
> Hello, @WenTingTseng @wuningxi when I run base_model_bert.py , i got this error
> `Traceback (most recent call last): File "base_model_bert.py", line 10, in <module> from src.models.tf_helpers import lookup_embedding,initialise_pretrained_embedding ModuleNotFoundError: No module named 'src'`
> 
> Even file system is properly arranged as per instructions in Readme.md
> Thanks a lot for help.

Hi @yugaljain1999,

This looks like a path issue. Not sure if you are working inside a programming environment or from the command line, but I would recommend using the command line for debugging and running the commands below. 

Using the command line, You need to be in tBERT directory when executing the code as the project is using relative paths based on the tBERT directory. Your error message indicates that python can't find the src folder which is directly located inside the tBERT project. 

First, go to the tBERT directory:
```
cd /path/to/tBERT
```
Then, verify that the tBERT directory contains the unpacked data folder and the src folder
```
ls
data  data.tar.gz  README.md  requirements.txt  src
```
From here, execute the model code (don't go the any of the subfolders)
```
python src/models/base_model_bert.py
```
If you are using a programming environment, you need to add the tBERT folder to your path.

**Comment by wuningxi** [comment]
> > Hi WenTing,
> > The easiest way is to download `https://www.dropbox.com/s/thhym7njtgp8uoh/data.tar.gz` as mentioned in the setup instructions. This already contains the preprocessed dataset files in the `cache/` folder. Please make sure that the tarball is placed in the tBERT directory and unpacked, so the model can find it. You can check this by going to your tBERT directory and type `ls data/cache/m_*.pickle` which should show you the three MSRP files:
> > `data/cache/m_dev_B.pickle data/cache/m_train_B.pickle data/cache/m_test_B.pickle`
> > Alternatively you can download the original datasets, place them in the respective dataset folders and process them from scratch.
> 
> hello,I want know where can download the original data sets.thank you !!

Hi @lattyjiang,

The original files come from the following sources:

MRSP: https://www.microsoft.com/en-us/download/details.aspx?id=52398
Quora: https://zhiguowang.github.io/
SemEval: http://alt.qcri.org/semeval2017/task3/index.php?id=data-and-tools
