### ISSUE TITLE
Thrown if the given repository appears to have an invalid format. 

### ISSUE THREAD

**Issue by zh57398** [wuningxi/tBERT#11]
Error:  Thrown if the given repository appears to have an invalid format.  
Traceback (most recent call last):
  File "src/models/base_model_bert.py", line 97, in model
    add_git_version(opt) # keep track of git SHA
  File "/home/he130/python_workspace/tbert/tBERT-master/src/models/helpers/base.py", line 8, in add_git_version
    opt['git'] = get_git_sha()
  File "/home/he130/python_workspace/tbert/tBERT-master/src/logs/training_logs.py", line 18, in get_git_sha
    repo = git.Repo(search_parent_directories=True)
  File "/home/he130/anaconda3/envs/tbert/lib/python3.6/site-packages/git/repo/base.py", line 168, in __init__
 raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /home/he130/python_workspace/tbert/tBERT-master
reading logs...
No file found at data/logs/test.json. Creating new log.
get new id

I have a problem as shown above. Is this a git problem? I did not find the relevant solution, want to consult you, hope to get your help, look forward to your answer, thank you very much!

**Comment by wuningxi** [comment]
When training a new model, a training log is created to record results for each model. This log also keeps track of the code version with which results were produced based on the SHA of the most recent git commit. It looks like you're getting the error message because your tBERT directory is not a git repository (you can check with `git status`). If that's the case, you should be able to solve the problem by creating a git repository (`git init`) and making an initial commit. Hope this helps.

**Comment by zh57398** [comment]
> 训练新模型时，将创建训练日志以记录每个模型的结果。该日志还跟踪基于最新git commit的SHA生成结果的代码版本。您似乎收到了错误消息，因为您的tBERT目录不是git存储库（可以使用查看`git status`）。在这种情况下，您应该可以通过创建git存储库（`git init`）并进行初始提交来解决问题。希望这可以帮助。

Thank you very much for your help. I have solved the problem.

**Comment by zh57398** [comment]
> When training a new model, a training log is created to record results for each model. This log also keeps track of the code version with which results were produced based on the SHA of the most recent git commit. It looks like you're getting the error message because your tBERT directory is not a git repository (you can check with `git status`). If that's the case, you should be able to solve the problem by creating a git repository (`git init`) and making an initial commit. Hope this helps.

Thank you very much for your help. I have solved the problem
