### ISSUE TITLE
On the use of Bert model

### ISSUE THREAD

**Issue by zh57398** [wuningxi/tBERT#12]
My machine can't connect to the network. I want to download the Bert model and place it for local use. However, the reference path is always incorrect. It is not the Bert in the following code_ Is the parameter berturl in lookup changed to local path?

BERT_ version = get_ bert_ version(cased,bert_ large)

BERT_ URL = ' https://tfhub.dev/google/bert_ {}/1'.format(BERT_ version)

print('Loading pretrained model from {}'.format(BERT_ URL))

bert_ lookup = hub.Module (BERT_ URL,name='bert_ lookup',trainable=bert_ update)

X_ embedded = bert_ lookup(bert_ inputs, signature="tokens", as_ dict=True

**Comment by zh57398** [comment]
I see that the Bert model has been downloaded locally in the project. How should I use the downloaded local Bert model? At present, there is no way to use it. I need your help urgently. Thank you very much.

**Comment by davidliuDDD** [comment]
BERT_ version = get_ bert_ version(cased,bert_ large)

BERT_ URL = ' https://tfhub.dev/google/bert_ {}/1'.format(BERT_ version)

print('Loading pretrained model from {}'.format(BERT_ URL))

bert_ lookup = hub.Module (BERT_ URL,name='bert_ lookup',trainable=bert_ update)

X_ embedded = bert_ lookup(bert_ inputs, signature="tokens", as_ dict=True


Hi, @zh57398 , I hava the same situations, how do you solve this problem?

**Comment by zh57398** [comment]
> BERT_ version = get_ bert_ version(cased,bert_ large)
> 
> BERT_ URL = ' https://tfhub.dev/google/bert_ {}/1'.format(BERT_ version)
> 
> print('Loading pretrained model from {}'.format(BERT_ URL))
> 
> bert_ lookup = hub.Module (BERT_ URL,name='bert_ lookup',trainable=bert_ update)
> 
> X_ embedded = bert_ lookup(bert_ inputs, signature="tokens", as_ dict=True
> 
> Hi, @zh57398 , I hava the same situations, how do you solve this problem?

I have tried many ways, but none of them have solved the problem. Do you have any good suggestions? Thank you very much.

**Comment by wuningxi** [comment]
I'm trying to reproduce your problem. Can you share your error message?

**Comment by zh57398** [comment]
> I'm trying to reproduce your problem. Can you share your error message?

![QQ图片20201209213855](https://user-images.githubusercontent.com/56859478/101637181-624a2180-3a67-11eb-83a6-3963095ca7b1.png)
![微信图片_20201209213935](https://user-images.githubusercontent.com/56859478/101637212-6bd38980-3a67-11eb-8809-f56c4d387466.jpg)
I downloaded Bert's uncased mentioned in readme_ L-12_ H-768_ A-12.zip model is placed in / home / TF hub cache, but base_ model_ bert.py Or to load the online model on the Internet, I think it's the code shown in the figure. He needs to pass the Bert_ URL finds the model and loads it. I will be Bert_ The URL is replaced by the address where the local model is stored (/ home / TF hub cache / uncased)_ L-12_ H-768_ A-12), but it seems that the code can't find him. There is an error in the second figure, so how can I load a local Bert model without using the Internet?
I changed the code in Figure 1 as follows(directly add Bert_ URL changed to local address):
        BERT_version = get_bert_version(cased,bert_large)
        print('Loading pretrained model from {}'.format(BERT_URL))
        bert_lookup = hub.Module('/home/guest09/tf-hub-cache/uncased_L-12_H-768_A-12',name='bert_lookup',trainable=bert_update)
        X_embedded = bert_lookup(bert_inputs, signature="tokens", as_dict=True)

**Comment by wuningxi** [comment]
The contents of `uncased_L-12_H-768_A-12.zip` are only used to read BERT's vocabulary. For offline usage, you need a different format which you can manually download with the following command:
```
wget https://storage.googleapis.com/tfhub-modules/google/bert_uncased_L-12_H-768_A-12/1.tar.gz -O bert_uncased_L-12_H-768_A-12_offline.tar.gz
```
Then untar its contents:
```
mkdir bert_uncased_L-12_H-768_A-12_offline && tar zxvf bert_uncased_L-12_H-768_A-12_offline.tar.gz -C bert_uncased_L-12_H-768_A-12_offline
```
Now, copy `bert_uncased_L-12_H-768_A-12_offline` to `/home/guest09/tf-hub-cache/` on your machine and update BERT_URL in `base_model_bert.py` to your local path, e.g.:
```
BERT_URL =  '/home/guest09/tf-hub-cache/bert_uncased_L-12_H-768_A-12_offline'
```

**Comment by zh57398** [comment]
> bert_uncased_L-12_H-768_A-12_offline'

Using your method, I have successfully completed the model training. Thank you from the bottom of my heart for your help.
But I have another problem, which is that when using the local Bert model, you mentioned the model that needs to be downloaded: "Bert"_ uncased_ L-12_ H-768_ A-12_ Is this type of model specifically used to load local Bert models? I didn't find this kind of model when I was looking for solutions on the Internet. All I found were models as shown in the figure. How can I determine which model I need to download? And where should I find the class you mentioned loading the Bert model locally, such as "Bert_ uncased_ L-12_ H-768_ A-12_ offline”？
![QQ截图20201210211503](https://user-images.githubusercontent.com/56859478/101778023-42316580-3b2e-11eb-962b-b4fe0851ad36.png)

**Comment by wuningxi** [comment]
`bert_uncased_L-12_H-768_A-12_offline.tar.gz` is just the result of renaming the output of `wget` using the `-O` flag for your convenience. The main difference is the model format: .pb instead of .ckpt (see https://stackoverflow.com/questions/56340852/distinguish-types-of-on-disk-models for information on different formats). The solution above is based on this [blog](https://medium.com/@xianbao.qian/how-to-run-tf-hub-locally-without-internet-connection-4506b850a915) which explains how to download tfhub models in .pb format for local use. Closing this as the problem appears to be solved.

**Comment by zh57398** [comment]
> `bert_uncased_L-12_H-768_A-12_offline.tar.gz` is just the result of renaming the output of `wget` using the `-O` flag for your convenience. The main difference is the model format: .pb instead of .ckpt (see https://stackoverflow.com/questions/56340852/distinguish-types-of-on-disk-models for information on different formats). The solution above is based on this [blog](https://medium.com/@xianbao.qian/how-to-run-tf-hub-locally-without-internet-connection-4506b850a915) which explains how to download tfhub models in .pb format for local use. Closing this as the problem appears to be solved.

Your answer has helped me a lot. I can understand this question now. Thank you for answering the question for me.

**Comment by cxx-cindy** [comment]
> `bert_uncased_L-12_H-768_A-12_offline.tar.gz` is just the result of renaming the output of `wget` using the `-O` flag for your convenience. The main difference is the model format: .pb instead of .ckpt (see https://stackoverflow.com/questions/56340852/distinguish-types-of-on-disk-models for information on different formats). The solution above is based on this [blog](https://medium.com/@xianbao.qian/how-to-run-tf-hub-locally-without-internet-connection-4506b850a915) which explains how to download tfhub models in .pb format for local use. Closing this as the problem appears to be solved.

您好，我想知道在windows下，这个命令怎样使用？搜了好多没有解决，希望您能跟我说一下！感谢！
