### ISSUE TITLE
No such file or directory: 'data/MSRP/MSRParaphraseCorpus/msr-para-train.tsv'

### ISSUE THREAD

**Issue by 460176980** [wuningxi/tBERT#2]
When I use “ python src/models/base_model_bert.py” , the project indicates that there are no files in the MSRP datasetI downloaded it data.tar.gz The size of the dataset is 280.21M . Did I download it wrong?

**Comment by wuningxi** [comment]
> When I use “ python src/models/base_model_bert.py” , the project indicates that there are no files in the MSRP datasetI downloaded it data.tar.gz The size of the dataset is 280.21M . Did I download it wrong?

Hi @460176980,

The size of data.tar.gz looks fine, although you still need to unpack it and make sure you're in the correct directory when running the code. Please have a look at https://github.com/wuningxi/tBERT/issues/1 as your question may have already been answered there or post your error message if it is a different one.
