### ISSUE TITLE
请问实验用的数据集可以公开吗？

### ISSUE THREAD

**Issue by clearlove999999** [wuningxi/tBERT#7]
我根据readme里的操作解压了data.tar.gz，但是里面的MSRP, Quora, Semeval和STS数据集都是空的，我在官方网站下载了MSRP后发现数据集格式并非tsv而是txt的。
因此可以分享一下您的实验数据集吗？

**Comment by wuningxi** [comment]
本来的data.tar.gz只包含已经处理过的cache。现在更新链接了，可以直接下载original_data.tar.gz。

**Comment by clearlove999999** [comment]
好的，非常感谢！



在 2020-11-14 01:35:44，"wuningxi" <notifications@github.com> 写道：

本来的data.tar.gz只包含已经处理过的cache。现在更新链接了，可以直接下载original_data.tar.gz。

**Comment by cxx-cindy** [comment]
您好，数据集下载了，但是出现这样的错误[Errno 2] No such file or directory: 'data/MSRP\\MSRParaphraseCorpus\\msr-para-train.tsv'
请问是自己解压还是用命令去解压？
