### ISSUE TITLE
关于数据的得下载

### ISSUE THREAD

**Issue by zh57398** [wuningxi/tBERT#9]
Is the dataset from this location https://www.dropbox.com/s/6p26mkwv62677zt/original_ data.tar.gz Get it? Is this the latest one? I can't open this website right now， Looking forward to your answer. Thank you very much.

**Comment by wuningxi** [comment]
The correct URL is https://www.dropbox.com/s/6p26mkwv62677zt/original_data.tar.gz (without the space). I double checked and the download is working fine for me.

**Comment by zh57398** [comment]
> 正确的URL是https://www.dropbox.com/s/6p26mkwv62677zt/original_data.tar.gz（不带空格）。我仔细检查过，下载对我来说很好。

I still can't open this link. Do you have any special requirements such as browser to open the link?
![QQ截图20201119104813](https://user-images.githubusercontent.com/56859478/99615126-d2135080-2a55-11eb-8bb6-f21cca90f2f6.png)
